apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efk-storage
  namespace: kube-logging
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-local-pv1
  namespace: kube-logging
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-storage
  local:
    path: /mnt/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gcdlusaws2ddo01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-local-pv2
  namespace: kube-logging
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-storage
  local:
    path: /mnt/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:              
          - gcdlusaws2ddo02    
